name: "📝 Simple Issue"
description: Create a new issue
title: "Request - "
labels: [
  "question"
]
body:

  - type: textarea
    id: summary
    attributes:
      label: "Summary"
      description: Provide a brief explanation of the feature
      placeholder: Describe in a few lines your feature request
    validations:
      required: true
  - type: textarea
    id: reference_issues
    attributes:
      label: "Reference Issues"
      description: Reference other issues
      placeholder: "#Issues IDs"
    validations:
      required: false
  - type: textarea
    id: basic_example
    attributes:
      label: "Basic Example"
      description: Indicate here some basic examples of your issue.
      placeholder: A few specific words about your issue.
    validations:
      required: false